### ISSUE TITLE
App terminates on startup 

### ISSUE THREAD

**Issue by Saad0011** [transistorsoft/flutter_background_geolocation_firebase#1]
After attaching the firebase plugin, app terminates on startup

**Comment by christocracy** [comment]
You’re giving me 0 info.

**Comment by HardikkMadaan** [comment]
The app terminates as soon as the slider is set to on mode.
`D/TSLocationManager(28456): [c.t.l.adapter.TSConfig c] ℹ️   Persist config, dirty: [debug, distanceFilter, logLevel, startOnBoot, stopOnTerminate, stopTimeout]
D/TSLocationManager(28456): [c.t.l.a.BackgroundGeolocation ready] LocationPermission :false
I/Choreographer(28456): Skipped 97 frames!  The application may be doing too much work on its main thread.
D/vndksupport(28456): Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
D/vndksupport(28456): Loading /vendor/lib64/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
I/OpenGLRenderer(28456): Davey! duration=1670ms; Flags=1, IntendedVsync=154799670868337, Vsync=154801287534939, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=154801295101087, AnimationStart=154801295195097, PerformTraversalsStart=154801295272701, DrawStart=154801304248431, SyncQueued=154801306621244, SyncStart=154801306887702, IssueDrawCommandsStart=154801307149005, SwapBuffers=154801339042914, FrameCompleted=154801341547081, DequeueBufferDuration=1026000, QueueBufferDuration=790000, 
E/EnhancedIntentService(28456): binding to the service failed
I/TSLocationManager(28456): [c.t.locationmanager.util.b a] 
I/TSLocationManager(28456):   🔵  LocationAuthorization: Requesting permission
D/AndroidRuntime(28456): Shutting down VM
E/AndroidRuntime(28456): FATAL EXCEPTION: main
E/AndroidRuntime(28456): Process: com.example.whatsupfirebase, PID: 28456
E/AndroidRuntime(28456): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.whatsupfirebase/com.intentfilter.androidpermissions.PermissionsActivity}; have you declared this activity in your AndroidManifest.xml?
E/AndroidRuntime(28456): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2012)
E/AndroidRuntime(28456): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1675)
E/AndroidRuntime(28456): 	at android.app.ContextImpl.startActivity(ContextImpl.java:917)
E/AndroidRuntime(28456): 	at android.app.ContextImpl.startActivity(ContextImpl.java:888)
E/AndroidRuntime(28456): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
E/AndroidRuntime(28456): 	at com.intentfilter.androidpermissions.PermissionManager.startPermissionActivity(PermissionManager.java:63)
E/AndroidRuntime(28456): 	at com.intentfilter.androidpermissions.PermissionHandler.requestPermissions(PermissionHandler.java:70)
E/AndroidRuntime(28456): 	at com.intentfilter.androidpermissions.PermissionHandler.checkPermissions(PermissionHandler.java:47)
E/AndroidRuntime(28456): 	at com.intentfilter.androidpermissions.PermissionManager.checkPermissions(PermissionManager.java:50)
E/AndroidRuntime(28456): 	at com.transistorsoft.locationmanager.util.b$2.run(Unknown Source:26)
E/AndroidRuntime(28456): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(28456): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(28456): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(28456): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/AndroidRuntime(28456): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28456): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
E/AndroidRuntime(28456): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/TSLocationManager(28456): [c.t.l.a.BackgroundGeolocation$e uncaughtException] 
E/TSLocationManager(28456):   ‼️  Uncaught Exception: Unable to find explicit activity class {com.example.whatsupfirebase/com.intentfilter.androidpermissions.PermissionsActivity}; have you declared this activity in your AndroidManifest.xml?
E/TSLocationManager(28456): {"activityRecognitionInterval":10000,"allowIdenticalLocations":false,"autoSync":true,"autoSyncThreshold":0,"batchSync":false,"debug":true,"deferTime":0,"desiredAccuracy":0,"desiredOdometerAccuracy":100,"disableElasticity":false,"disableLocationAuthorizationAlert":false,"disableStopDetection":false,"distanceFilter":50,"elasticityMultiplier":1,"enableHeadless":false,"enableTimestampMeta":false,"extras":{},"fastestLocationUpdateInterval":-1,"forceReloadOnBoot":false,"forceReloadOnGeofence":false,"forceReloadOnHeartbeat":false,"forceReloadOnLocationChange":false,"forceReloadOnMotionChange":false,"forceReloadOnSchedule":false,"foregroundService":true,"geofenceInitialTriggerEntry":true,"geofenceModeHighAccuracy":false,"geofenceProximityRadius":1000,"geofenceTemplate":"","headers":{},"headlessJobService":"com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask","heartbeatInterval":-1,"httpRootProperty":"location","httpTimeout":60000,"isMoving":false,"locationTemplate":"","locationTimeout":60,"locationUpdateInterval":1000,"locationsOrderDirection":"ASC","logLevel":5,"logMaxDays":3,"maxBatchSize":-1,"maxDaysToPersist":1,"maxRecordsToPersist":-1,"method":"POST","minimumActivityRecognitionConfidence":75,"notification":{"layout":"","title":"","text":"Location Service activated","color":"","channelName":"TSLocationManager","smallIcon":"","largeIcon":"","priority":0,"strings":{},"actions":[]},"params":{},"persist":true,"persistMode":2,"schedule":[],"scheduleUseAlarmManager":false,"speedJumpFilter":300,"startOnBoot":true,"stationaryRadius":25,"stopAfterElapsedMinutes":0,"stopOnStationary":false,"stopOnTerminate":false,"stopTimeout":1,"triggerActivities":"in_vehicle, on_bicycle, on_foot, running, walking","url":"","useSignificantChangesOnly":false,"enabled":false,"schedulerEnabled":false,"trackingMode":1,"odometer":0,"isFirstBoot":true}
E/TSLocationManager(28456): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.whatsupfirebase/com.intentfilter.androidpermissions.PermissionsActivity}; have you declared this activity in your AndroidManifest.xml?
E/TSLocationManager(28456): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2012)
E/TSLocationManager(28456): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1675)
E/TSLocationManager(28456): 	at android.app.ContextImpl.startActivity(ContextImpl.java:917)
E/TSLocationManager(28456): 	at android.app.ContextImpl.startActivity(ContextImpl.java:888)
E/TSLocationManager(28456): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
E/TSLocationManager(28456): 	at com.intentfilter.androidpermissions.PermissionManager.startPermissionActivity(PermissionManager.java:63)
E/TSLocationManager(28456): 	at com.intentfilter.androidpermissions.PermissionHandler.requestPermissions(PermissionHandler.java:70)
E/TSLocationManager(28456): 	at com.intentfilter.androidpermissions.PermissionHandler.checkPermissions(PermissionHandler.java:47)
E/TSLocationManager(28456): 	at com.intentfilter.androidpermissions.PermissionManager.checkPermissions(PermissionManager.java:50)
E/TSLocationManager(28456): 	at com.transistorsoft.locationmanager.util.b$2.run(Unknown Source:26)
E/TSLocationManager(28456): 	at android.os.Handler.handleCallback(Handler.java:873)
E/TSLocationManager(28456): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/TSLocationManager(28456): 	at android.os.Looper.loop(Looper.java:193)
E/TSLocationManager(28456): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/TSLocationManager(28456): 	at java.lang.reflect.Method.invoke(Native Method)
E/TSLocationManager(28456): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
E/TSLocationManager(28456): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process (28456): Sending signal. PID: 28456 SIG: 9`

This is the state of the debug console.
Running the exact same code as there in example/lib/main.dart

**Comment by christocracy** [comment]
Post a new issue.  I need info from the issue template.  The OP ignored the issue template.
